### PR TITLE
fix:#568 - Fix restrict date selection available slots

### LINKED ISSUE #568: [BUG] Restrict Date Selection to Available Slots
**Description:**

Currently, when creating a prompt and selecting a date, the user is able to choose any date, even those that already have scheduled prompts. This leads to confusion and potential conflicts when scheduling prompts on the same date.

**Expected Behavior:**

The date picker should only allow users to select from available slots.
Dates that already have prompts scheduled should be grayed out and unselectable.

**Steps to Reproduce:**

Start creating a new prompt.
Attempt to select any date from the date picker, even if it has a prompt.
Observe that there is no restriction, allowing selection of unavailable dates. 
_(The check is made only at the submit which is annoying)_

**Proposed Solution:**

Implement a check in datepicker for available slots.
Disable and gray out dates that already have prompts, preventing user selection.
Optionally, display a tooltip or indication explaining why certain dates are unavailable.

### PR DESCRIPTION
**Pull request by sana7044**
### 🛠 Description
This PR addresses the issue of restricting date selection in the prompt creation interface to only available dates, avoiding conflicts with already scheduled prompts.

#### Implementation Details:

1. Component Updates:

- `MonthPicker.vue`: Implemented logic to disable and gray out dates that have already scheduled prompts, preventing users from selecting these dates.
- `PromptCard.vue`: Updated the date selection portion to use this restricted date picker, ensuring only available months can be selected.

2. Logic Enhancements:

- Mounted and Submit Logic: Adjusted `onMounted` and `onSubmit` hooks to account for the restricted date logic and prevent submitting prompts on unavailable dates.
- Date Picker Fix: The original date picker setting `:options="(date) => date >= '2023/11/01'"` was not working due to format or logic issues. This was fixed to properly restrict dates to on or after November 1,2023. 

3. `Prompts.js`:

- Added a new function, `getPromptDates`, which retrieves an array of unavailable months as strings. This function helps ensure the prompt creation interface only shows open slots for selection.

4. User Experience Improvements:

- Prompt Card Skeleton: Displayed a loading skeleton in the prompt card for a smoother UX while fetching data.
- Auto-Selection of Next Available Month: When the user starts creating a prompt, the date picker now auto-selects the next available month, streamlining the prompt scheduling process.

Fixes #568 

### ✨ Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### 🧠 Rationale behind the change

Why did you choose to make these changes? Were there any trade-offs you had to consider?

### 🧪 All Test Suites Passed?

- [x] Manual tested
- [ ] Vitest
- [x] Cypress

**Testing Notes:**

- Verified that unavailable dates are correctly grayed out and unselectable.
- Tested auto-selection of the next available month to ensure it works as intended.
- Confirmed the fix for `:options="(date) => date >= '2023/11/01'" ` work as intended, allowing selection only dates on or after November 1,2023.

### 📸 Screenshots (optional)

Screenshot from 2024-11-04 11-07-09
Screenshot from 2024-11-04 11-10-04

### 🏎 Quick checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by marclupanc** [comment]
I would also restrict posting prompts for passed months, even if there are no prompts. But we might add it in the future. Just a thought...

File: src/components/Admin/PromptCard.vue [hunk 1]
```diff
@@ -4,133 +4,150 @@
...
-                      <q-date
-                        default-view="Months"
-                        emit-immediately
-                        :key="dataKey"
-                        mask="YYYY-MM"
-                        minimal
-                        :options="(date) => date >= '2023/11/01'"
-                        v-model="prompt.date"
-                        years-in-month-view
-                        @update:model-value="onUpdateMonth"
```
Comment (marclupanc) [inline src/components/Admin/PromptCard.vue:32]: When removing section, make sure to also remove all the unused functions

File: src/stores/prompts.js [hunk 2]
```diff
@@ -241,6 +241,15 @@ export const usePromptStore = defineStore('prompts', {
...
 
+    async getPromptDates() {
+      const set = new Set()
+      await this.fetchPrompts()
+      this.getPrompts?.map((prompt) => {
+        set.add(prompt?.id)
+      })
+      return Array.from(set)
+    },
+
```
Comment (marclupanc) [inline src/stores/prompts.js:252]: There is an issue that can be reproduced as follose:
1. Open Vue Tab in Google Chrome Dev Tools
2. Open Pinia section/Root/prompts
3. Navigate to Search page
4. Observe it is loading 6 items initially
5. When scrolling to load more, it loads all the rest available and stops fetching from firebase (that's also visible in network tab)
6. Open Create prompt dialog
7. Close dialog
8. Scroll down on the search page
9. Observe it restarts the fetching of prompts

Comment (sana7044) [reply src/stores/prompts.js:252]: I will look into it

Comment (sana7044) [reply src/stores/prompts.js:255]: @marclupanc Yes, I have fixed this issue, please check it.

**Comment by sana7044** [comment]
@marclupanc , the test case is failing coz we are not able to create the entry for the prompts for which escrow id is not yet generated.

**Review by marclupanc — APPROVED** [review]
