### PR TITLE
bug: Added a 404 Redirect

### LINKED ISSUE #43: Handle 404 on prompt page
if we load a prompt page py sending it a wrong id who don't exist in the store and in firestore, we don't have a 404 Error.
Instead of this we have a broken page. 

image

### PR DESCRIPTION
**Pull request by stravid87**
If a user now types "www.celebrityfanalyzer.com/<non-existent slug>", the default behavior is to redirect to a 404 page.
I was thinking to add it to the .route.js file as a "before check" but decided against because it would require a redundant check to the Pinia, prompStore. (see the commented out lines in route.js)
 
The downside of using the redirect is that for a split second, the user is transferred to the PromptPage.vue I doubt this is an issue but maybe? 

Finally, I added an explicit path: '/404' as a top level route. 

Because `path: ':slug' ` catches everything, the ` path: '/:catchAll(.*)*', ` currently used in the route.js file may be redundant.

Thoughts?

Fix #43

### CODE REVIEW

**Review by arnonrdp — COMMENTED** [review]
Simple solution, I like it.

I could see your branch here in my IDE. You are probably using a remote other than `origin`.
Also, the deployment wasn't done, so I couldn't test it.

But there's not much to see, your solution is good and it was better to check for existence via conditional in `PromptPage.vue` than via `beforeRouteEnter` in `routes.js`.

File: src/router/routes.js [hunk 1]
```diff
@@ -24,6 +24,10 @@ const routes = [
       {
         path: ':slug',
         component: () => import('pages/PromptPage.vue')
+        // beforeEnter: (_to, _from, next) => {
+        //   let condition = 'fail'
+        //   condition != 'fail' ? next('/404') : next()
+        // }
```
Comment (arnonrdp) [inline src/router/routes.js:30]: This comment can be removed.

File: src/router/routes.js [hunk 2]
```diff
@@ -48,6 +52,10 @@ const routes = [
       }
     ]
   },
+  {
+    path: '/404',
+    component: () => import('pages/404Error.vue')
+  },
   {
     path: '/:catchAll(.*)*',
     component: () => import('pages/404Error.vue')
```
Comment (arnonrdp) [inline src/router/routes.js:61]: You can merge these two items using `alias`:

```suggestion
  {
    path: '/:catchAll(.*)*',
    alias: '/404',
    component: () => import('pages/404Error.vue')
  }
```

**Review by arnonrdp — CHANGES_REQUESTED** [review]

File: src/pages/PromptPage.vue [hunk 3]
```diff
@@ -92,6 +92,9 @@ async function updatePrompt() {
   } else if (router.currentRoute.value.params.slug) {
     prompt.value = promptStore.getPrompts.find((prompt) => prompt.slug === router.currentRoute.value.params.slug)
   }
+  if (prompt.value == undefined) {
+    router.push('/404')
+  }
```
Comment (hermannleboss) [inline src/pages/PromptPage.vue:97]: This can lead to an error. beacause We retrieve the value of prompt asynchronously.

The second reason is prompt default value is and empty object, and it's change to `undefine` only with the output off find function when it doesn't found the prompt. 

So we can have this only for `:slug` route.

**Review by hermannleboss — CHANGES_REQUESTED** [review]

File: src/stores/prompts.js [hunk 4]
```diff
@@ -60,20 +60,20 @@ export const usePromptStore = defineStore('prompts', {
...
-          prompt.author = await getDoc(prompt.author).then((doc) => doc.data())
-
-          this._prompts = this.getPrompts
-          const index = this._prompts.findIndex((p) => p.id === prompt.id)
-
-          if (index === -1) this._prompts.push(prompt)
-          else this._prompts[index] = prompt
-
-          return prompt
+          if (doc.data == undefined) {
```
Comment (stravid87) [inline src/stores/prompts.js:63]: The addition of this "if check" should be a good thing in general anywhere "fetchPromptById()" is invoked.

File: src/pages/PromptPage.vue (hunk 3 above)
Comment (stravid87) [reply src/pages/PromptPage.vue]: What are your thoughts? I ran a quick test and it appears that because the 'await' keyword is invoked  before the `promptStore` function call, the added if check won't run until the `promptStore` returns.
I threw together this test to see if it works as expected even though the await keywork is nested

`(async () => {
  let global;
  if(true){
    await new Promise((res, rej) => { // with 'await'
      //res('RESOLVED')
      rej("REJECTED")
    }).then((data)=>{
      global = data;  // data assigment in 'then block' also awaited.
    }).catch(err => {
      global = err
      console.log(err)
    })
  }
  console.log('[global variable: ]', global) // no error
})();`

**Review by hermannleboss — APPROVED** [review]
It's good, 
@arnonrdp do you have something to add ?

**Review by arnonrdp — APPROVED** [review]
